// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: multiplica/multiplica.proto

package multiplica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number1 int32 `protobuf:"varint,1,opt,name=Number1,proto3" json:"Number1,omitempty"`
	Number2 int32 `protobuf:"varint,2,opt,name=Number2,proto3" json:"Number2,omitempty"`
}

func (x *MessageIn) Reset() {
	*x = MessageIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplica_multiplica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIn) ProtoMessage() {}

func (x *MessageIn) ProtoReflect() protoreflect.Message {
	mi := &file_multiplica_multiplica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIn.ProtoReflect.Descriptor instead.
func (*MessageIn) Descriptor() ([]byte, []int) {
	return file_multiplica_multiplica_proto_rawDescGZIP(), []int{0}
}

func (x *MessageIn) GetNumber1() int32 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *MessageIn) GetNumber2() int32 {
	if x != nil {
		return x.Number2
	}
	return 0
}

type MessageOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *MessageOut) Reset() {
	*x = MessageOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multiplica_multiplica_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOut) ProtoMessage() {}

func (x *MessageOut) ProtoReflect() protoreflect.Message {
	mi := &file_multiplica_multiplica_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOut.ProtoReflect.Descriptor instead.
func (*MessageOut) Descriptor() ([]byte, []int) {
	return file_multiplica_multiplica_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOut) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_multiplica_multiplica_proto protoreflect.FileDescriptor

var file_multiplica_multiplica_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2f, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x22, 0x3f, 0x0a, 0x09, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x31,
	0x12, 0x18, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x22, 0x24, 0x0a, 0x0a, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x4c, 0x0a, 0x0b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x72, 0x12,
	0x3d, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x12, 0x15, 0x2e,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x17,
	0x5a, 0x15, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x2f, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multiplica_multiplica_proto_rawDescOnce sync.Once
	file_multiplica_multiplica_proto_rawDescData = file_multiplica_multiplica_proto_rawDesc
)

func file_multiplica_multiplica_proto_rawDescGZIP() []byte {
	file_multiplica_multiplica_proto_rawDescOnce.Do(func() {
		file_multiplica_multiplica_proto_rawDescData = protoimpl.X.CompressGZIP(file_multiplica_multiplica_proto_rawDescData)
	})
	return file_multiplica_multiplica_proto_rawDescData
}

var file_multiplica_multiplica_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiplica_multiplica_proto_goTypes = []interface{}{
	(*MessageIn)(nil),  // 0: multiplica.MessageIn
	(*MessageOut)(nil), // 1: multiplica.MessageOut
}
var file_multiplica_multiplica_proto_depIdxs = []int32{
	0, // 0: multiplica.Multiplicar.Multiplica:input_type -> multiplica.MessageIn
	1, // 1: multiplica.Multiplicar.Multiplica:output_type -> multiplica.MessageOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiplica_multiplica_proto_init() }
func file_multiplica_multiplica_proto_init() {
	if File_multiplica_multiplica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multiplica_multiplica_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multiplica_multiplica_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multiplica_multiplica_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multiplica_multiplica_proto_goTypes,
		DependencyIndexes: file_multiplica_multiplica_proto_depIdxs,
		MessageInfos:      file_multiplica_multiplica_proto_msgTypes,
	}.Build()
	File_multiplica_multiplica_proto = out.File
	file_multiplica_multiplica_proto_rawDesc = nil
	file_multiplica_multiplica_proto_goTypes = nil
	file_multiplica_multiplica_proto_depIdxs = nil
}
